# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # "npm" value supports both npm & yarn, see documentation for possible values
    directory: "/" # Location of package manifest
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm" 
    directory: "/packages/web-app" 
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm" 
    directory: "/packages/eslint-config" 
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm" 
    directory: "/packages/prettier-config" 
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm" 
    directory: "/packages/typescript-config" 
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm" 
    directory: "/packages/eslint-config"-typescript 
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
