import React, { useState, useCallback, useEffect, useRef } from 'react';
import PropTypes from 'prop-types';
import { useIntl } from 'react-intl';
import {
  Box,
  Button,
  Card,
  CardActionArea,
  CardContent,
  Checkbox,
  CircularProgress,
  Divider,
  IconButton,
  Stack,
  Tooltip,
  Typography
} from '@mui/material';
import ChevronRightIcon from '@mui/icons-material/ChevronRight';
import SearchOffIcon from '@mui/icons-material/SearchOff';
import VisibilityIcon from '@mui/icons-material/Visibility';
import AppLink from '../AppLink';
import Translate from '../Translate';
import { useLongPress } from '../../../hooks/useLongPress';

const MobileEntityCard = React.memo(
  ({
    doc,
    columns,
    link,
    renderCellFn,
    icon,
    selected = false,
    onToggle = null,
    onRowClick = null
  }) => {
    const { formatMessage } = useIntl();
    const longPressFiredRef = useRef(false);
    const titleCol =
      columns.find(c => c.isTitle) ??
      columns.find(c => c.field === 'name' || c.field === 'title') ??
      columns[0];
    const bodyColumns = columns.filter(c => c !== titleCol);

    // Selection mode (onToggle set): a short tap toggles selection. When a
    // preview is also available (onRowClick set), the card offers two extra
    // ways to reach it — a dedicated icon button and a long-press — mirroring
    // desktop's "checkbox = select, row = preview" split.
    // Outside selection mode the card is a real navigation link.
    const canPreview = Boolean(onToggle && onRowClick);

    const rawLongPress = useLongPress(() => {
      if (!canPreview) return;
      longPressFiredRef.current = true;
      onRowClick(doc);
    });
    // Reset the fired flag at the start of every new touch so a long-press
    // that doesn't produce a follow-up click event can't block the next tap.
    const longPressHandlers = canPreview
      ? {
          ...rawLongPress,
          onTouchStart: e => {
            longPressFiredRef.current = false;
            rawLongPress.onTouchStart(e);
          },
          onTouchCancel: e => {
            longPressFiredRef.current = false;
            rawLongPress.onTouchCancel(e);
          }
        }
      : null;

    const handleClick = () => {
      if (longPressFiredRef.current) {
        longPressFiredRef.current = false;
        return;
      }
      if (onToggle) onToggle(doc.id);
      else if (onRowClick) onRowClick(doc);
    };

    const handlePreviewClick = e => {
      e.stopPropagation();
      onRowClick(doc);
    };

    // A preview may intercept the compatibility click after a long press.
    // Reset for a fresh mouse/pen or keyboard activation, while preserving
    // suppression of the click generated by the original touch gesture.
    const handlePointerDown = e => {
      if (e.pointerType !== 'touch') longPressFiredRef.current = false;
    };
    const handleKeyDown = () => {
      longPressFiredRef.current = false;
    };

    return (
      <Card
        sx={{
          outline: '1px solid',
          outlineColor: 'primary.main',
          bgcolor: selected ? 'action.selected' : 'background.paper',
          transition: 'background-color 0.15s'
        }}>
        <Box sx={{ display: 'flex', alignItems: 'stretch' }}>
          <CardActionArea
            onClick={handleClick}
            onPointerDown={handlePointerDown}
            onKeyDown={handleKeyDown}
            {...(longPressHandlers ?? {})}
            {...(!onToggle
              ? { component: AppLink, to: link(doc), openInNewTabDesktop: true }
              : {})}
            sx={{ flex: 1, minWidth: 0 }}>
            <CardContent
              sx={{
                py: 0.5,
                '&:last-child': { pb: 1 }
              }}>
              <Box
                sx={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between'
                }}>
                <Box
                  sx={{
                    display: 'flex',
                    alignItems: 'center',
                    minWidth: 0
                  }}>
                  {onToggle && (
                    <Checkbox
                      checked={selected}
                      size="small"
                      color="primary"
                      onClick={e => e.stopPropagation()}
                      onTouchStart={e => e.stopPropagation()}
                      onTouchMove={e => e.stopPropagation()}
                      onTouchEnd={e => e.stopPropagation()}
                      onTouchCancel={e => e.stopPropagation()}
                      onChange={() => onToggle(doc.id)}
                      sx={{
                        p: 0.25,
                        flexShrink: 0
                      }}
                    />
                  )}
                  {typeof icon === 'function' ? icon(doc) : icon}
                  <Typography
                    variant="subtitle1"
                    color="secondary"
                    sx={{
                      fontWeight: 'bold',
                      fontSize: '0.9375rem',
                      lineHeight: 1.3
                    }}>
                    {renderCellFn(doc, titleCol.field, titleCol.render)}
                  </Typography>
                </Box>
                {!onToggle && (
                  <ChevronRightIcon
                    fontSize="small"
                    sx={{
                      color: 'text.disabled',
                      flexShrink: 0
                    }}
                  />
                )}
              </Box>
              <Divider />
              {bodyColumns.length > 0 && (
                <Box
                  sx={{
                    display: 'flex',
                    flexDirection: 'column'
                  }}>
                  {bodyColumns.map(col => {
                    const value = renderCellFn(doc, col.field, col.render);
                    const isMissing = value === '-';
                    return (
                      <Box
                        key={col.field}
                        sx={{
                          display: 'flex',
                          alignItems: 'center',
                          gap: 0.5
                        }}>
                        <Typography
                          variant="caption"
                          sx={{
                            color: 'text.secondary',
                            minWidth: '35%',
                            flexShrink: 0
                          }}>
                          <Translate>{col.label}</Translate>
                        </Typography>
                        <Typography
                          variant="body2"
                          sx={{
                            color: isMissing ? 'text.disabled' : 'text.primary',
                            fontWeight: isMissing ? 'normal' : 500
                          }}>
                          {value}
                        </Typography>
                      </Box>
                    );
                  })}
                </Box>
              )}
            </CardContent>
          </CardActionArea>
          {canPreview && (
            <Tooltip title={formatMessage({ id: 'Preview' })}>
              <IconButton
                color="primary"
                onClick={handlePreviewClick}
                aria-label={formatMessage({ id: 'Preview' })}
                sx={{
                  alignSelf: 'center',
                  mx: 0.5,
                  flexShrink: 0
                }}>
                <VisibilityIcon />
              </IconButton>
            </Tooltip>
          )}
        </Box>
      </Card>
    );
  }
);

MobileEntityCard.displayName = 'MobileEntityCard';

MobileEntityCard.propTypes = {
  doc: PropTypes.shape({
    id: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
  }).isRequired,
  columns: PropTypes.arrayOf(PropTypes.shape({})).isRequired,
  link: PropTypes.func.isRequired,
  renderCellFn: PropTypes.func.isRequired,
  // When a function, called with the row data to allow per-row icons
  icon: PropTypes.oneOfType([PropTypes.node, PropTypes.func]),
  selected: PropTypes.bool,
  onToggle: PropTypes.func,
  onRowClick: PropTypes.func
};

// ~600 cards ≈ 30 "Load more" clicks × 20 rows/page, capped to prevent DOM bloat on mobile.
const MAX_ACCUMULATED_ROWS = 600;

const MobileEntityList = ({
  rows,
  columns,
  totalRows,
  isLoading,
  isNewQuery,
  onPageChange,
  rowsPerPage,
  link,
  icon,
  renderCellFn,
  onSelected = null,
  selectedIds: controlledSelectedIds,
  onRowClick = null
}) => {
  const [allRows, setAllRows] = useState(rows ?? []);
  const [page, setPage] = useState(0);
  const [internalSelectedIds, setInternalSelectedIds] = useState([]);
  const selectedIds = controlledSelectedIds ?? internalSelectedIds;
  const isSelectionControlled = controlledSelectedIds !== undefined;
  const isAppending = useRef(false);
  const hasInteracted = useRef(false);
  // Keep callback changes from retriggering the internal selection effect.
  const onSelectedRef = useRef(onSelected);
  onSelectedRef.current = onSelected;

  useEffect(() => {
    if (!isNewQuery) return;
    setAllRows([]);
    setPage(0);
    setInternalSelectedIds([]);
    if (isSelectionControlled && onSelectedRef.current) {
      onSelectedRef.current([]);
    }
    hasInteracted.current = false;
    isAppending.current = false;
  }, [isNewQuery, isSelectionControlled]);

  useEffect(() => {
    if (isAppending.current) {
      setAllRows(prev => {
        const next = [...prev, ...(rows ?? [])];
        return next.length > MAX_ACCUMULATED_ROWS
          ? next.slice(0, MAX_ACCUMULATED_ROWS)
          : next;
      });
    } else {
      setAllRows(rows ?? []);
    }
    isAppending.current = false;
  }, [rows]);

  // Notify parent only when selection actually changes, not on mount.
  // Uncontrolled path only: controlled mode notifies through handleToggle and
  // never writes internalSelectedIds, so this effect stays idle.
  useEffect(() => {
    if (!hasInteracted.current) return;
    if (onSelectedRef.current) onSelectedRef.current(internalSelectedIds);
  }, [internalSelectedIds]);

  // In controlled mode the parent owns the selection, so report the next
  // value directly. Existing callers keep the internal-state behavior.
  const handleToggle = useCallback(
    id => {
      const nextSelectedIds = selectedIds.includes(id)
        ? selectedIds.filter(selectedId => selectedId !== id)
        : [...selectedIds, id];

      if (isSelectionControlled) {
        if (onSelectedRef.current) onSelectedRef.current(nextSelectedIds);
        return;
      }

      hasInteracted.current = true;
      setInternalSelectedIds(nextSelectedIds);
    },
    [isSelectionControlled, selectedIds]
  );

  const handleLoadMore = () => {
    isAppending.current = true;
    const nextPage = page + 1;
    setPage(nextPage);
    if (onPageChange) onPageChange(nextPage, rowsPerPage);
  };

  const hasMore =
    totalRows != null &&
    allRows.length < totalRows &&
    allRows.length < MAX_ACCUMULATED_ROWS;

  if (allRows.length === 0 && !isLoading) {
    return (
      <Box sx={{ py: 3, textAlign: 'center', color: 'text.disabled' }}>
        <SearchOffIcon sx={{ fontSize: 48, mb: 0.5 }} />
        <Typography
          variant="body2"
          sx={{
            color: 'text.secondary'
          }}>
          <Translate>No results</Translate>
        </Typography>
        <Typography
          variant="caption"
          sx={{
            color: 'text.disabled'
          }}>
          <Translate>Try adjusting your search or filters</Translate>
        </Typography>
      </Box>
    );
  }

  return (
    <Box>
      <Stack spacing={1} sx={{ mb: 0.5 }}>
        {allRows.map(doc => (
          <MobileEntityCard
            key={doc.id}
            doc={doc}
            columns={columns}
            link={link}
            icon={icon}
            renderCellFn={renderCellFn}
            selected={onSelected ? selectedIds.includes(doc.id) : false}
            onToggle={onSelected ? handleToggle : null}
            onRowClick={onRowClick}
          />
        ))}
      </Stack>
      {(hasMore || isLoading) && (
        <Box sx={{ display: 'flex', justifyContent: 'center', py: 1 }}>
          {isLoading ? (
            <CircularProgress size={24} color="secondary" />
          ) : (
            <Button variant="outlined" onClick={handleLoadMore}>
              <Translate>Load more</Translate>
              {` (${allRows.length} / ${totalRows})`}
            </Button>
          )}
        </Box>
      )}
      {!hasMore && allRows.length >= MAX_ACCUMULATED_ROWS && (
        <Typography
          variant="caption"
          sx={{
            color: 'text.secondary',
            display: 'block',
            textAlign: 'center',
            py: 0.5
          }}>
          <Translate>Refine your search to see more results</Translate>
        </Typography>
      )}
    </Box>
  );
};

MobileEntityList.propTypes = {
  rows: PropTypes.arrayOf(PropTypes.shape({})),
  columns: PropTypes.arrayOf(PropTypes.shape({})).isRequired,
  totalRows: PropTypes.number,
  isLoading: PropTypes.bool,
  isNewQuery: PropTypes.bool,
  onPageChange: PropTypes.func,
  rowsPerPage: PropTypes.number.isRequired,
  link: PropTypes.func.isRequired,
  // When a function, called with the row data to allow per-row icons
  icon: PropTypes.oneOfType([PropTypes.node, PropTypes.func]),
  renderCellFn: PropTypes.func.isRequired,
  onSelected: PropTypes.func,
  selectedIds: PropTypes.arrayOf(
    PropTypes.oneOfType([PropTypes.number, PropTypes.string])
  ),
  onRowClick: PropTypes.func
};

export default MobileEntityList;
